In [31]:
import pandas as pd 

df = pd.read_csv("results_cleaned.csv")

In [32]:
home_games = df.groupby("home_team").size()
print(home_games.head(10))

home_team
Abkhazia                17
Afghanistan             40
Albania                139
Alderney                47
Algeria                208
American Samoa          25
Andorra                 82
Angola                 128
Anguilla                24
Antigua and Barbuda     94
dtype: int64

In [33]:
home_wins = df[df["result"] == "home_win"].groupby("home_team").size()
print(home_wins.head(10))

home_team
Abkhazia                 9
Afghanistan             13
Albania                 42
Alderney                 1
Algeria                135
American Samoa           3
Andorra                  5
Angola                  69
Anguilla                 2
Antigua and Barbuda     34
dtype: int64

In [34]:
home_win_rate = home_wins / home_games
print(home_win_rate.head(10))

home_team
Abkhazia               0.529412
Afghanistan            0.325000
Albania                0.302158
Alderney               0.021277
Algeria                0.649038
American Samoa         0.120000
Andorra                0.060976
Angola                 0.539062
Anguilla               0.083333
Antigua and Barbuda    0.361702
dtype: float64

In [35]:
away_games = df.groupby("away_team").size()
print(away_games.head(10))

away_team
Abkhazia            9
Afghanistan        71
Albania           138
Alderney           85
Algeria           173
Ambazonia           4
American Samoa     29
Andorra            85
Angola            140
Anguilla           50
dtype: int64

In [36]:
away_wins = df[df["result"] == "away_win"].groupby("away_team").size()
print(away_wins.head(10))

away_team
Abkhazia                3
Afghanistan            15
Albania                23
Alderney                4
Algeria                53
American Samoa          1
Andorra                 2
Angola                 28
Anguilla                3
Antigua and Barbuda    16
dtype: int64

In [37]:
away_win_rate = away_wins / away_games
print(away_win_rate.head(10))

away_team
Abkhazia          0.333333
Afghanistan       0.211268
Albania           0.166667
Alderney          0.047059
Algeria           0.306358
Ambazonia              NaN
American Samoa    0.034483
Andorra           0.023529
Angola            0.200000
Anguilla          0.060000
dtype: float64

In [38]:
home_goal_difference = df.groupby("home_team")["home_score"].sum() - df.groupby("home_team")["away_score"].sum()
print(home_goal_difference.head(10))

home_goal_difference_rate = home_goal_difference / home_games
print(home_goal_difference_rate.head(10))

home_team
Abkhazia                25.0
Afghanistan            -19.0
Albania                -34.0
Alderney              -179.0
Algeria                282.0
American Samoa        -133.0
Andorra               -157.0
Angola                 105.0
Anguilla               -60.0
Antigua and Barbuda    -12.0
dtype: float64
home_team
Abkhazia               1.470588
Afghanistan           -0.475000
Albania               -0.244604
Alderney              -3.808511
Algeria                1.355769
American Samoa        -5.320000
Andorra               -1.914634
Angola                 0.820312
Anguilla              -2.500000
Antigua and Barbuda   -0.127660
dtype: float64

In [39]:
away_goal_difference = df.groupby("away_team")["away_score"].sum() - df.groupby("away_team")["home_score"].sum()
print(away_goal_difference.head(10))

away_goal_difference_rate = away_goal_difference / away_games
print(away_goal_difference_rate.head(10))

away_team
Abkhazia            2.0
Afghanistan      -106.0
Albania          -178.0
Alderney         -359.0
Algeria           -18.0
Ambazonia         -12.0
American Samoa   -185.0
Andorra          -218.0
Angola            -54.0
Anguilla         -204.0
dtype: float64
away_team
Abkhazia          0.222222
Afghanistan      -1.492958
Albania          -1.289855
Alderney         -4.223529
Algeria          -0.104046
Ambazonia        -3.000000
American Samoa   -6.379310
Andorra          -2.564706
Angola           -0.385714
Anguilla         -4.080000
dtype: float64

In [40]:
df["home_team_win_rate"] = df["home_team"].map(home_win_rate)
df["away_team_win_rate"] = df["away_team"].map(away_win_rate)
df["home_team_goal_difference_rate"] = df["home_team"].map(home_goal_difference_rate)
df["away_team_goal_difference_rate"] = df["away_team"].map(away_goal_difference)

In [41]:
df = df.dropna(subset=['home_team_win_rate', 'away_team_win_rate'])

In [42]:
df.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,result,home_team_win_rate,away_team_win_rate,home_team_goal_difference_rate,away_team_goal_difference_rate
0,1884-01-26,Northern Ireland,Scotland,0.0,5.0,British Home Championship,Belfast,Ireland,False,away_win,0.347985,0.387417,-0.369963,35.0
1,1884-02-09,Wales,Northern Ireland,6.0,0.0,British Home Championship,Wrexham,Wales,False,home_win,0.403571,0.177258,0.114286,-373.0
2,1884-02-23,Northern Ireland,England,1.0,8.0,British Home Championship,Belfast,Ireland,False,away_win,0.347985,0.535826,-0.369963,357.0
3,1884-03-15,Scotland,England,1.0,0.0,British Home Championship,Glasgow,Scotland,False,home_win,0.591362,0.535826,0.996678,357.0
4,1884-03-17,Wales,England,0.0,4.0,British Home Championship,Wrexham,Wales,False,away_win,0.403571,0.535826,0.114286,357.0

In [43]:
df["neutral"] = df["neutral"].astype(int)

In [44]:
features = ["home_team_win_rate", 
            "away_team_win_rate", 
            "neutral", 
            "tournament",
            "home_team_goal_difference_rate",
            "away_team_goal_difference_rate"]
target = "result"

X = df[features]
y = df[target]

In [45]:
from sklearn.preprocessing import LabelEncoder

X = X.copy()
le_tournament = LabelEncoder()

X["tournament"] = le_tournament.fit_transform(X["tournament"])

In [46]:
X.head()

,home_team_win_rate,away_team_win_rate,neutral,tournament,home_team_goal_difference_rate,away_team_goal_difference_rate
0,0.347985,0.387417,0,27,-0.369963,35.0
1,0.403571,0.177258,0,27,0.114286,-373.0
2,0.347985,0.535826,0,27,-0.369963,357.0
3,0.591362,0.535826,0,27,0.996678,357.0
4,0.403571,0.535826,0,27,0.114286,357.0

In [47]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state =42, stratify = y)

In [48]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

In [49]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train_resampled, y_train_resampled)

RandomForestClassifier(random_state=42)

In [50]:
predictions = rf_model.predict(X_test)

In [51]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

accuracy = accuracy_score(y_test, predictions)
report = classification_report(y_test, predictions)

print(f"Accuracy: {accuracy:.2f}")
print("Classification Report:")
print(report)

Accuracy: 0.53
Classification Report:
              precision    recall  f1-score   support

    away_win       0.50      0.52      0.51      1772
        draw       0.26      0.27      0.27      1321
    home_win       0.66      0.65      0.65      3092

    accuracy                           0.53      6185
   macro avg       0.48      0.48      0.48      6185
weighted avg       0.53      0.53      0.53      6185

In [52]:
import joblib

joblib.dump(rf_model, "world_cup_rf_model.pkl")
joblib.dump(le_tournament, "tournament_label_encoder.pkl")
joblib.dump(home_win_rate, "home_win_rate.pkl")
joblib.dump(away_win_rate, "away_win_rate.pkl")
joblib.dump(home_goal_difference_rate, "home_goal_difference_rate.pkl")
joblib.dump(away_goal_difference_rate, "away_goal_difference_rate.pkl")

['away_goal_difference_rate.pkl']

In [53]:
print(rf_model.feature_names_in_)

['home_team_win_rate' 'away_team_win_rate' 'neutral' 'tournament'
 'home_team_goal_difference_rate' 'away_team_goal_difference_rate']

In [54]:
sorted(df["home_team"].unique().tolist())

['Abkhazia',
 'Afghanistan',
 'Albania',
 'Alderney',
 'Algeria',
 'American Samoa',
 'Andorra',
 'Angola',
 'Anguilla',
 'Antigua and Barbuda',
 'Arameans Suryoye',
 'Argentina',
 'Armenia',
 'Artsakh',
 'Aruba',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas',
 'Bahrain',
 'Bangladesh',
 'Barawa',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bermuda',
 'Bhutan',
 'Biafra',
 'Bolivia',
 'Bonaire',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'British Virgin Islands',
 'Brittany',
 'Brunei',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Cape Verde',
 'Cascadia',
 'Cayman Islands',
 'Central African Republic',
 'Chad',
 'Chameria',
 'Chile',
 'China',
 'Colombia',
 'Comoros',
 'Congo',
 'Cook Islands',
 'Corsica',
 'Costa Rica',
 'County of Nice',
 'Croatia',
 'Cuba',
 'Curaçao',
 'Cyprus',
 'Czech Republic',
 'Czechoslovakia',
 'DR Congo',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'Délvidék',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Ellan Vannin',
 'England',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Eswatini',
 'Ethiopia',
 'Falkland Islands',
 'Faroe Islands',
 'Felvidék',
 'Fiji',
 'Finland',
 'France',
 'French Guiana',
 'Frøya',
 'Gabon',
 'Gambia',
 'Georgia',
 'German DR',
 'Germany',
 'Ghana',
 'Gibraltar',
 'Gotland',
 'Gozo',
 'Greece',
 'Greenland',
 'Grenada',
 'Guadeloupe',
 'Guam',
 'Guatemala',
 'Guernsey',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Hitra',
 'Hmong',
 'Honduras',
 'Hong Kong',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Iraqi Kurdistan',
 'Isle of Man',
 'Isle of Wight',
 'Israel',
 'Italy',
 'Ivory Coast',
 'Jamaica',
 'Japan',
 'Jersey',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kernow',
 'Kosovo',
 'Kurdistan',
 'Kuwait',
 'Kyrgyzstan',
 'Kárpátalja',
 'Laos',
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Liechtenstein',
 'Lithuania',
 'Luxembourg',
 'Macau',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Mapuche',
 'Martinique',
 'Matabeleland',
 'Mauritania',
 'Mauritius',
 'Mayotte',
 'Menorca',
 'Mexico',
 'Moldova',
 'Mongolia',
 'Montenegro',
 'Montserrat',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nepal',
 'Netherlands',
 'New Caledonia',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'North Korea',
 'North Macedonia',
 'North Vietnam',
 'Northern Cyprus',
 'Northern Ireland',
 'Northern Mariana Islands',
 'Norway',
 'Occitania',
 'Oman',
 'Orkney',
 'Padania',
 'Pakistan',
 'Palestine',
 'Panama',
 'Panjab',
 'Papua New Guinea',
 'Paraguay',
 'Parishes of Jersey',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Provence',
 'Puerto Rico',
 'Qatar',
 'Quebec',
 'Raetia',
 'Republic of Ireland',
 'Republic of St. Pauli',
 'Rhodes',
 'Romania',
 'Russia',
 'Rwanda',
 'Réunion',
 'Saare County',
 'Saint Kitts and Nevis',
 'Saint Lucia',
 'Saint Martin',
 'Saint Vincent and the Grenadines',
 'Samoa',
 'San Marino',
 'Saudi Arabia',
 'Scotland',
 'Senegal',
 'Serbia',
 'Seychelles',
 'Shetland',
 'Sierra Leone',
 'Singapore',
 'Sint Maarten',
 'Slovakia',
 'Slovenia',
 'Solomon Islands',
 'Somalia',
 'Somaliland',
 'South Africa',
 'South Korea',
 'South Ossetia',
 'South Sudan',
 'Spain',
 'Sri Lanka',
 'Sudan',
 'Suriname',
 'Sweden',
 'Switzerland',
 'Syria',
 'Székely Land',
 'Sápmi',
 'São Tomé and Príncipe',
 'Tahiti',
 'Taiwan',
 'Tajikistan',
 'Tamil Eelam',
 'Tanzania',
 'Thailand',
 'Timor-Leste',
 'Togo',
 'Tonga',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Turks and Caicos Islands',
 'Tuvalu',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Koreans in Japan',
 'United States',
 'United States Virgin Islands',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Venezuela',
 'Vietnam',
 'Vietnam Republic',
 'Wales',
 'Wallis Islands and Futuna',
 'Western Armenia',
 'Western Australia',
 'Western Isles',
 'Western Sahara',
 'Yemen',
 'Ynys Môn',
 'Yugoslavia',
 'Zambia',
 'Zanzibar',
 'Zimbabwe',
 'Åland Islands']

In [55]:
print(le_tournament.classes_)

['ABCS Tournament' 'AFC Asian Cup' 'AFC Asian Cup qualification'
 'AFC Challenge Cup' 'AFC Challenge Cup qualification'
 'AFC Solidarity Cup' 'AFF Championship' 'AFF Championship qualification'
 'ASEAN Championship' 'ASEAN Championship qualification'
 'African Cup of Nations' 'African Cup of Nations qualification'
 'African Friendship Games' 'Afro-Asian Games' 'Al Ain International Cup'
 'All-African Games' 'Amílcar Cabral Cup' 'Arab Cup'
 'Arab Cup qualification' 'Asian Games' 'Atlantic Cup'
 'Atlantic Heritage Cup' 'Balkan Cup' 'Baltic Cup'
 'Beijing International Friendship Tournament' 'Bolivarian Games'
 'Brazil Independence Cup' 'British Home Championship' 'CAFA Nations Cup'
 'CCCF Championship' 'CECAFA Cup' 'CFU Caribbean Cup'
 'CFU Caribbean Cup qualification' 'CONCACAF Championship'
 'CONCACAF Championship qualification' 'CONCACAF Nations League'
 'CONCACAF Nations League qualification' 'CONCACAF Series'
 'CONIFA Africa Football Cup' 'CONIFA Asia Cup'
 'CONIFA European Football Cup' 'CONIFA South America Football Cup'
 'CONIFA World Cup qualification' 'CONIFA World Football Cup'
 'CONIFA World Football Cup qualification'
 'CONMEBOL–UEFA Cup of Champions' 'COSAFA Cup' 'COSAFA Cup qualification'
 'Canadian Shield' 'Central American and Caribbean Games'
 'Central European International Cup' 'ConIFA Challenger Cup'
 'Confederations Cup' 'Copa América' 'Copa América qualification'
 'Copa Artigas' "Copa Bernardo O'Higgins" 'Copa Carlos Dittborn'
 'Copa Chevallier Boutell' 'Copa Confraternidad' 'Copa Félix Bogado'
 'Copa Juan Pinto Durán' 'Copa Lipton' 'Copa Newton' 'Copa Oswaldo Cruz'
 'Copa Paz del Chaco' 'Copa Premio Honor Argentino'
 'Copa Premio Honor Uruguayo' 'Copa Ramón Castilla' 'Copa Rio Branco'
 'Copa Roca' 'Copa del Pacífico' 'Corsica Cup' "Coupe de l'Outre-Mer"
 'Cup of Ancient Civilizations' 'Cyprus International Tournament'
 'Dakar Tournament' 'Diamond Jubilee International Football Tournament'
 'Dragon Cup' 'Dunhill Cup' 'Dynasty Cup' 'EAFF Championship'
 'EAFF Championship qualification' 'ELF Cup' 'East Asian Games'
 'FIFA 75th Anniversary Cup' 'FIFA Series' 'FIFA World Cup'
 'FIFA World Cup qualification' 'FIFI Wild Cup'
 'Far Eastern Championship Games' 'Four Nations Tournament'
 "Four Nations' Cup" 'GaNEFo' 'Gold Cup' 'Gold Cup qualification'
 'Great Wall Cup' 'Guangzhou International Friendship Tournament'
 'Gulf Cup' 'Hungary Heritage Cup' 'Indian Ocean Island Games'
 'Indonesia Tournament' 'Inter Games' 'Inter-Allied Games'
 'Intercontinental Cup'
 'International Tournament of Peoples, Cultures and Tribes' 'Island Games'
 'Joe Robbie Cup' 'Jordan International Tournament'
 'King Hassan II Tournament' "King's Cup" 'Kirin Challenge Cup'
 'Kirin Cup' 'Korea Cup' 'Kuneitra Cup' 'Lunar New Year Cup'
 "MSG Prime Minister's Cup" 'Mahinda Rajapaksa Cup'
 'Malta International Tournament' 'Mapinduzi Cup' 'Marianas Cup'
 'Marlboro Cup' 'Matthews Cup' 'Mauritius Four Nations Cup'
 'Melanesia Cup' 'Merdeka Tournament' 'Merlion Cup' 'Miami Cup'
 'Millennium Cup' 'Morocco, Capital of African Football'
 'Mukuru 4 Nations' 'Mundialito' 'Muratti Vase' 'NAFC Championship'
 'NAFU Championship' 'Nations Cup' 'Navruz Cup' 'Nehru Cup'
 'Niamh Challenge Cup' 'Nile Basin Tournament' 'Nordic Championship'
 'OSN Cup' 'Oceania Nations Cup' 'Oceania Nations Cup qualification'
 'Olympic Games' 'Open International Championship'
 'Outrigger Challenge Cup' 'Pacific Games' 'Pacific Mini Games'
 'Palestine Cup' 'Palestine International Championship'
 'Pan American Championship' 'Peace Cup' 'Philippine Peace Cup'
 'Phillip Seaga Cup' "Prime Minister's Cup"
 'Real Madrid 75th Anniversary Cup' 'Rous Cup' 'SAFF Cup'
 'SKN Football Festival' 'Scania 100 Tournament' 'Simba Tournament'
 'Soccer Ashes' 'South Asian Games' 'South Asian Super Cup'
 'South Pacific Games' 'South Pacific Mini Games' 'Southeast Asian Games'
 'Southeast Asian Peninsular Games' 'Superclásico de las Américas'
 'TIFOCO Tournament' 'The Other Final' 'Three Nations Cup'
 'Tournament Burkina Faso' 'Tournoi de France' 'Trans-Tasman Cup'
 'Tri Nation Tournament' 'Tri-Nations Cup' 'Tri-Nations Series'
 'Tynwald Hill Tournament' 'UDEAC Cup' 'UEFA Euro'
 'UEFA Euro qualification' 'UEFA Nations League' 'UNCAF Cup' 'UNIFFAC Cup'
 'USA Cup' 'United Arab Emirates Friendship Tournament' 'Unity Cup'
 'VFF Cup' 'Vietnam Independence Cup' 'Viva World Cup' 'WAFF Championship'
 'West African Cup' 'Windward Islands Tournament' 'World Unity Cup'
 'Zambian Independence Tournament' 'Évence Coppée Trophy']

In [56]:
[t for t in le_tournament.classes_ if 'World Cup' in t]

['CONIFA World Cup qualification',
 'FIFA World Cup',
 'FIFA World Cup qualification',
 'Viva World Cup']

In [57]:
print(sorted(df["home_team"].unique().tolist()))

['Abkhazia', 'Afghanistan', 'Albania', 'Alderney', 'Algeria', 'American Samoa', 'Andorra', 'Angola', 'Anguilla', 'Antigua and Barbuda', 'Arameans Suryoye', 'Argentina', 'Armenia', 'Artsakh', 'Aruba', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barawa', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bermuda', 'Bhutan', 'Biafra', 'Bolivia', 'Bonaire', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'British Virgin Islands', 'Brittany', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon', 'Canada', 'Cape Verde', 'Cascadia', 'Cayman Islands', 'Central African Republic', 'Chad', 'Chameria', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo', 'Cook Islands', 'Corsica', 'Costa Rica', 'County of Nice', 'Croatia', 'Cuba', 'Curaçao', 'Cyprus', 'Czech Republic', 'Czechoslovakia', 'DR Congo', 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'Délvidék', 'Ecuador', 'Egypt', 'El Salvador', 'Ellan Vannin', 'England', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia', 'Falkland Islands', 'Faroe Islands', 'Felvidék', 'Fiji', 'Finland', 'France', 'French Guiana', 'Frøya', 'Gabon', 'Gambia', 'Georgia', 'German DR', 'Germany', 'Ghana', 'Gibraltar', 'Gotland', 'Gozo', 'Greece', 'Greenland', 'Grenada', 'Guadeloupe', 'Guam', 'Guatemala', 'Guernsey', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Hitra', 'Hmong', 'Honduras', 'Hong Kong', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Iraqi Kurdistan', 'Isle of Man', 'Isle of Wight', 'Israel', 'Italy', 'Ivory Coast', 'Jamaica', 'Japan', 'Jersey', 'Jordan', 'Kazakhstan', 'Kenya', 'Kernow', 'Kosovo', 'Kurdistan', 'Kuwait', 'Kyrgyzstan', 'Kárpátalja', 'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Macau', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Mapuche', 'Martinique', 'Matabeleland', 'Mauritania', 'Mauritius', 'Mayotte', 'Menorca', 'Mexico', 'Moldova', 'Mongolia', 'Montenegro', 'Montserrat', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nepal', 'Netherlands', 'New Caledonia', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North Korea', 'North Macedonia', 'North Vietnam', 'Northern Cyprus', 'Northern Ireland', 'Northern Mariana Islands', 'Norway', 'Occitania', 'Oman', 'Orkney', 'Padania', 'Pakistan', 'Palestine', 'Panama', 'Panjab', 'Papua New Guinea', 'Paraguay', 'Parishes of Jersey', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Provence', 'Puerto Rico', 'Qatar', 'Quebec', 'Raetia', 'Republic of Ireland', 'Republic of St. Pauli', 'Rhodes', 'Romania', 'Russia', 'Rwanda', 'Réunion', 'Saare County', 'Saint Kitts and Nevis', 'Saint Lucia', 'Saint Martin', 'Saint Vincent and the Grenadines', 'Samoa', 'San Marino', 'Saudi Arabia', 'Scotland', 'Senegal', 'Serbia', 'Seychelles', 'Shetland', 'Sierra Leone', 'Singapore', 'Sint Maarten', 'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia', 'Somaliland', 'South Africa', 'South Korea', 'South Ossetia', 'South Sudan', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Syria', 'Székely Land', 'Sápmi', 'São Tomé and Príncipe', 'Tahiti', 'Taiwan', 'Tajikistan', 'Tamil Eelam', 'Tanzania', 'Thailand', 'Timor-Leste', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan', 'Turks and Caicos Islands', 'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Koreans in Japan', 'United States', 'United States Virgin Islands', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela', 'Vietnam', 'Vietnam Republic', 'Wales', 'Wallis Islands and Futuna', 'Western Armenia', 'Western Australia', 'Western Isles', 'Western Sahara', 'Yemen', 'Ynys Môn', 'Yugoslavia', 'Zambia', 'Zanzibar', 'Zimbabwe', 'Åland Islands']

In [58]:
print(sorted(df["tournament"].unique().tolist()))

['ABCS Tournament', 'AFC Asian Cup', 'AFC Asian Cup qualification', 'AFC Challenge Cup', 'AFC Challenge Cup qualification', 'AFC Solidarity Cup', 'AFF Championship', 'AFF Championship qualification', 'ASEAN Championship', 'ASEAN Championship qualification', 'African Cup of Nations', 'African Cup of Nations qualification', 'African Friendship Games', 'Afro-Asian Games', 'Al Ain International Cup', 'All-African Games', 'Amílcar Cabral Cup', 'Arab Cup', 'Arab Cup qualification', 'Asian Games', 'Atlantic Cup', 'Atlantic Heritage Cup', 'Balkan Cup', 'Baltic Cup', 'Beijing International Friendship Tournament', 'Bolivarian Games', 'Brazil Independence Cup', 'British Home Championship', 'CAFA Nations Cup', 'CCCF Championship', 'CECAFA Cup', 'CFU Caribbean Cup', 'CFU Caribbean Cup qualification', 'CONCACAF Championship', 'CONCACAF Championship qualification', 'CONCACAF Nations League', 'CONCACAF Nations League qualification', 'CONCACAF Series', 'CONIFA Africa Football Cup', 'CONIFA Asia Cup', 'CONIFA European Football Cup', 'CONIFA South America Football Cup', 'CONIFA World Cup qualification', 'CONIFA World Football Cup', 'CONIFA World Football Cup qualification', 'CONMEBOL–UEFA Cup of Champions', 'COSAFA Cup', 'COSAFA Cup qualification', 'Canadian Shield', 'Central American and Caribbean Games', 'Central European International Cup', 'ConIFA Challenger Cup', 'Confederations Cup', 'Copa América', 'Copa América qualification', 'Copa Artigas', "Copa Bernardo O'Higgins", 'Copa Carlos Dittborn', 'Copa Chevallier Boutell', 'Copa Confraternidad', 'Copa Félix Bogado', 'Copa Juan Pinto Durán', 'Copa Lipton', 'Copa Newton', 'Copa Oswaldo Cruz', 'Copa Paz del Chaco', 'Copa Premio Honor Argentino', 'Copa Premio Honor Uruguayo', 'Copa Ramón Castilla', 'Copa Rio Branco', 'Copa Roca', 'Copa del Pacífico', 'Corsica Cup', "Coupe de l'Outre-Mer", 'Cup of Ancient Civilizations', 'Cyprus International Tournament', 'Dakar Tournament', 'Diamond Jubilee International Football Tournament', 'Dragon Cup', 'Dunhill Cup', 'Dynasty Cup', 'EAFF Championship', 'EAFF Championship qualification', 'ELF Cup', 'East Asian Games', 'FIFA 75th Anniversary Cup', 'FIFA Series', 'FIFA World Cup', 'FIFA World Cup qualification', 'FIFI Wild Cup', 'Far Eastern Championship Games', 'Four Nations Tournament', "Four Nations' Cup", 'GaNEFo', 'Gold Cup', 'Gold Cup qualification', 'Great Wall Cup', 'Guangzhou International Friendship Tournament', 'Gulf Cup', 'Hungary Heritage Cup', 'Indian Ocean Island Games', 'Indonesia Tournament', 'Inter Games', 'Inter-Allied Games', 'Intercontinental Cup', 'International Tournament of Peoples, Cultures and Tribes', 'Island Games', 'Joe Robbie Cup', 'Jordan International Tournament', 'King Hassan II Tournament', "King's Cup", 'Kirin Challenge Cup', 'Kirin Cup', 'Korea Cup', 'Kuneitra Cup', 'Lunar New Year Cup', "MSG Prime Minister's Cup", 'Mahinda Rajapaksa Cup', 'Malta International Tournament', 'Mapinduzi Cup', 'Marianas Cup', 'Marlboro Cup', 'Matthews Cup', 'Mauritius Four Nations Cup', 'Melanesia Cup', 'Merdeka Tournament', 'Merlion Cup', 'Miami Cup', 'Millennium Cup', 'Morocco, Capital of African Football', 'Mukuru 4 Nations', 'Mundialito', 'Muratti Vase', 'NAFC Championship', 'NAFU Championship', 'Nations Cup', 'Navruz Cup', 'Nehru Cup', 'Niamh Challenge Cup', 'Nile Basin Tournament', 'Nordic Championship', 'OSN Cup', 'Oceania Nations Cup', 'Oceania Nations Cup qualification', 'Olympic Games', 'Open International Championship', 'Outrigger Challenge Cup', 'Pacific Games', 'Pacific Mini Games', 'Palestine Cup', 'Palestine International Championship', 'Pan American Championship', 'Peace Cup', 'Philippine Peace Cup', 'Phillip Seaga Cup', "Prime Minister's Cup", 'Real Madrid 75th Anniversary Cup', 'Rous Cup', 'SAFF Cup', 'SKN Football Festival', 'Scania 100 Tournament', 'Simba Tournament', 'Soccer Ashes', 'South Asian Games', 'South Asian Super Cup', 'South Pacific Games', 'South Pacific Mini Games', 'Southeast Asian Games', 'Southeast Asian Peninsular Games', 'Superclásico de las Américas', 'TIFOCO Tournament', 'The Other Final', 'Three Nations Cup', 'Tournament Burkina Faso', 'Tournoi de France', 'Trans-Tasman Cup', 'Tri Nation Tournament', 'Tri-Nations Cup', 'Tri-Nations Series', 'Tynwald Hill Tournament', 'UDEAC Cup', 'UEFA Euro', 'UEFA Euro qualification', 'UEFA Nations League', 'UNCAF Cup', 'UNIFFAC Cup', 'USA Cup', 'United Arab Emirates Friendship Tournament', 'Unity Cup', 'VFF Cup', 'Vietnam Independence Cup', 'Viva World Cup', 'WAFF Championship', 'West African Cup', 'Windward Islands Tournament', 'World Unity Cup', 'Zambian Independence Tournament', 'Évence Coppée Trophy']

In [59]:
df[df["home_team"] == "Uzbekistan"].shape
df[df["away_team"] == "Uzbekistan"].shape

(112, 14)

In [61]:
print("Home win rate:", home_win_rate.get("Uzbekistan"))
print("Away win rate:", away_win_rate.get("Uzbekistan"))
print("Home goal diff:", home_goal_difference_rate.get("Uzbekistan"))
print("Away goal diff:", away_goal_difference_rate.get("Uzbekistan"))

Home win rate: 0.6504854368932039
Away win rate: 0.49107142857142855
Home goal diff: 1.5048543689320388
Away goal diff: 0.49107142857142855